### ISSUE TITLE
Add/delete card

### ISSUE THREAD

**Issue by wrudnicki16** [wrudnicki16/brainhacker#18]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug free navigation
- [ ] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
Awesome, looks great! No feedback on this MVP. There was a problem with the login page though, I had to click demo twice to make it work. Make sure you're preventing default on the session form.
