### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by wrudnicki16** [wrudnicki16/brainhacker#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
Can you add a heroku link to your wiki so I can find it? Thanks!

**Comment by niartenyaw** [comment]
Nice, looks great!

## Functionality

- [ ] Have the logo and `Brainhacker` text link back to `/` or the relevant home page
- [ ] `Already a user? Login` links me to `logout`
- [ ] `https://brainhacker1.herokuapp.com/#/eriguberoinvoerin` should redirect me to a usable URL
- [ ] Need to display errors to the user. Don't forget to clear errors when moving between `login` and `signup`
- [ ] Need a demo login

## Styling

- [ ] The size of the form changes when switching between session form types, moving everything on the page
- [ ] For the header text, I would probably center-justify them, not left-justify
- [ ] Give more padding to just about everything (buttons, inputs, form container), the form and all its components feel cramped

**Comment by wrudnicki16** [comment]
Can you explain what you mean by the header text? Theres the nav and the left part of the main page and the Login/Signup headers. I assume you mean the nav header though.

**Comment by wrudnicki16** [comment]
Also why do we need the login link to redirect us to logout? I'm a little confused by what I should be doing for that one

**Comment by niartenyaw** [comment]
Yeah, for the header text, I want to be able to click the logo or text in the left side of the nav and go to `/`

For the login link, I am currently being redirected to `/logout` but it should redirect me to `login`

**Comment by niartenyaw** [comment]
Awesome, you can close!
