### ISSUE TITLE
Decks - add/delete

### ISSUE THREAD

**Issue by wrudnicki16** [wrudnicki16/brainhacker#8]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
Looks great! One small thing to consider

## Styling

- [ ] I feel like the border line should be below the input box for the title. I wasn't sure where it was.

**Comment by wrudnicki16** [comment]
That makes sense, I was styling it like evernote, where they have tags above. I can change it for now because that makes more sense with nothing else there.
